from __future__ import annotations

from .nba import NBA_CANONICAL_TO_PLAYER_MARKET, NBA_MARKET_REGISTRY

WNBA_MARKET_REGISTRY = dict(NBA_MARKET_REGISTRY)
WNBA_CANONICAL_TO_PLAYER_MARKET = dict(NBA_CANONICAL_TO_PLAYER_MARKET)
