from __future__ import annotations

import json
import os
from datetime import datetime, timedelta
from pathlib import Path

from .base import EventInfo, ResultsProvider, TeamResult


class JsonResultsProvider(ResultsProvider):
    """Production-shaped provider that reads schedule/boxscore snapshots from JSON.

    This keeps the provider abstraction realistic without forcing a paid sports API
    during local development. You can point these env vars at files generated by a
    poller or any ETL job:
    - RESULTS_EVENTS_PATH
    - RESULTS_PLAYER_RESULTS_PATH
    """

    def __init__(self) -> None:
        events_path = os.getenv('RESULTS_EVENTS_PATH')
        player_path = os.getenv('RESULTS_PLAYER_RESULTS_PATH')
        if not events_path or not player_path:
            raise RuntimeError('RESULTS_EVENTS_PATH and RESULTS_PLAYER_RESULTS_PATH are required for RESULTS_PROVIDER=json')
        self._events = self._load_json(events_path)
        self._player_results = self._load_json(player_path)

    def _load_json(self, path_str: str) -> dict:
        path = Path(path_str)
        with open(path, 'r', encoding='utf-8') as fh:
            data = json.load(fh)
        return data

    def _event_info(self, event_id: str) -> EventInfo:
        row = self._events[event_id]
        start_time = row['start_time']
        if isinstance(start_time, str):
            start_time = datetime.fromisoformat(start_time)
        return EventInfo(
            event_id=event_id,
            sport=row['sport'],
            home_team=row['home_team'],
            away_team=row['away_team'],
            start_time=start_time,
        )

    def _candidate_events_for_team(self, team: str) -> list[EventInfo]:
        return sorted(
            [self._event_info(event_id) for event_id, row in self._events.items() if team in {row['home_team'], row['away_team']}],
            key=lambda item: item.start_time,
        )

    def _candidate_events_for_player(self, player: str) -> list[EventInfo]:
        return sorted(
            [self._event_info(event_id) for event_id, box in self._player_results.items() if player in box],
            key=lambda item: item.start_time,
        )

    def _resolve_by_time(self, events: list[EventInfo], as_of: datetime | None) -> EventInfo | None:
        if not events:
            return None
        if as_of is None:
            return events[0]
        future_buffer = timedelta(hours=8)
        future_candidates = [e for e in events if as_of <= e.start_time <= as_of + future_buffer]
        if future_candidates:
            return min(future_candidates, key=lambda item: item.start_time)
        recent_past = [e for e in events if e.start_time <= as_of <= e.start_time + timedelta(hours=8)]
        if recent_past:
            return max(recent_past, key=lambda item: item.start_time)
        historical = [e for e in events if e.start_time <= as_of]
        if historical:
            return max(historical, key=lambda item: item.start_time)
        return min(events, key=lambda item: item.start_time)

    def resolve_team_event(self, team: str, as_of: datetime | None) -> EventInfo | None:
        return self._resolve_by_time(self._candidate_events_for_team(team), as_of)

    def resolve_player_event(self, player: str, as_of: datetime | None) -> EventInfo | None:
        return self._resolve_by_time(self._candidate_events_for_player(player), as_of)

    def get_team_result(self, team: str, event_id: str | None = None) -> TeamResult | None:
        if event_id is None:
            return None
        row = self._events.get(event_id)
        if not row or team not in {row['home_team'], row['away_team']}:
            return None
        return TeamResult(event=self._event_info(event_id), moneyline_win=(row['moneyline_winner'] == team))

    def get_player_result(self, player: str, market_type: str, event_id: str | None = None) -> float | None:
        if event_id is None:
            return None
        box = self._player_results.get(event_id) or {}
        player_row = box.get(player) or {}
        value = player_row.get(market_type)
        return float(value) if value is not None else None
